apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: httpd
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      name: httpd-2
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd
          image: httpd:latest 
